# Generated by Django 4.0.3 on 2022-05-08 09:53

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_tweet_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tweets.tweet', verbose_name='Является ответом на твит'),
        ),
    ]
