# Generated by Django 4.0.3 on 2022-05-29 16:42

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0006_users_parents_field'),
        ('tweets', '0003_tags_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetUsers_Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='users_parents',
            field=models.ManyToManyField(blank=True, related_name='+', through='tweets.TweetUsers_Parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='related_tweets',
            field=models.ManyToManyField(blank=True, related_name='related_tags', to='tweets.tweet', verbose_name='Связанные твиты'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=140, unique=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='tweetusers_parents',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='tweetusers_parents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
