# Generated by Django 4.0.3 on 2022-04-24 19:13

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_tweet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='photos/default.png/', upload_to=authorization.models.get_profile_photo_path, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_name',
            field=models.CharField(max_length=50, verbose_name='Имя профиля'),
        ),
    ]
