# Generated by Django 4.0.3 on 2022-05-19 11:26

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', django.contrib.postgres.fields.citext.CICharField(max_length=140, unique=True, verbose_name='Тэг')),
                ('related_tweets', models.ManyToManyField(blank=True, related_name='related_tags', to='tweets.tweet', verbose_name='Связанные тэги')),
            ],
        ),
    ]
